/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VolunteerWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Entity.User;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.VaccineShootRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author fengpeng
 */
public class TestAppoinmentViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TestAppoinmentViewJPanel
     */
    private JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;
    private WorkRequest newRequest;
    private User selectedUser;
    private SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    public TestAppoinmentViewJPanel() {
    }

    TestAppoinmentViewJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, EcoSystem system, WorkRequest newRequest, User selectedUser) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.system = system;
        this.newRequest = newRequest;
        this.selectedUser = selectedUser;
        
        jLabel3.setText(userAccount.getUsername());
        txtDetail.setText(((VaccineShootRequest)newRequest).getVaccine().getDetail());
        txtHospital.setText(((VaccineShootRequest)newRequest).getHospital().getName());
        int size = ((VaccineShootRequest)newRequest).getVaccine().getPhases().size();
        txtDescription.setText(((VaccineShootRequest)newRequest).getVaccine().getPhases().get(size-1).getDescription());
        txtPhase.setText(((VaccineShootRequest)newRequest).getVaccine().getPhases().get(size-1).getName());
        txtVaccine.setText(((VaccineShootRequest)newRequest).getVaccine().getVaccineName());
        txtVaccineType.setText(((VaccineShootRequest)newRequest).getVaccine().getVaccineType());
        txtCreateTime.setText(ft.format(((VaccineShootRequest)newRequest).getVaccine().getCreatedTime()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtVaccine = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtVaccineType = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPhase = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCreateTime = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtHospital = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetail = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Vaccine: ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 191, 110, 34));
        add(txtVaccine, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 189, 128, 39));

        jLabel5.setText("Vaccine Type: ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 248, 110, 34));
        add(txtVaccineType, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 246, 128, 39));

        jLabel6.setText("Description: ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 271, 110, 34));
        add(txtPhase, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 189, 128, 39));

        jLabel7.setText("Create Time: ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 297, 110, 34));

        txtCreateTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreateTimeActionPerformed(evt);
            }
        });
        add(txtCreateTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 295, 128, 39));

        jLabel8.setText("Details: ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 419, 110, 34));

        jLabel9.setText("Hospital: ");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 354, 110, 34));
        add(txtHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 352, 128, 39));

        txtDetail.setColumns(20);
        txtDetail.setRows(5);
        jScrollPane1.setViewportView(txtDetail);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 419, -1, -1));

        jLabel10.setText("Phase: ");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 191, 110, 34));

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane2.setViewportView(txtDescription);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 271, -1, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Appointment Information");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 98, 724, 33));

        btnCancel.setBackground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 468, -1, 43));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 68, -1, 43));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setText("Volunteer");

        jLabel2.setText("Welcome: ");

        jLabel3.setText("Volunteer Username");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Appointment2.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 480, 220));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        ((VaccineShootRequest)newRequest).getHospital().getUserDirectory().getUserList().remove(selectedUser);
        if (system.getWorkQueue().getWorkRequestList().remove(newRequest)) {
            
            selectedUser.setVaccine(null);
            txtCreateTime.setText("");
            txtDescription.setText("");
            txtDetail.setText("");
            txtHospital.setText("");
            txtPhase.setText("");
            txtVaccine.setText("");
            txtVaccineType.setText("");
            JOptionPane.showMessageDialog(null, "Cancel the appoinmnet successfully.");
        } else {
            JOptionPane.showMessageDialog(null, "You are not cancel successfully.");
        }
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtCreateTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreateTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreateTimeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtCreateTime;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextArea txtDetail;
    private javax.swing.JTextField txtHospital;
    private javax.swing.JTextField txtPhase;
    private javax.swing.JTextField txtVaccine;
    private javax.swing.JTextField txtVaccineType;
    // End of variables declaration//GEN-END:variables
}
