/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ScientistWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Entity.Phase;
import Business.Entity.Vaccine;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author fengpeng
 */
public class VaccineInfoJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;
    private Vaccine v1;
    private SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    /**
     * Creates new form VaccineInfoJPanel
     */
    public VaccineInfoJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem system, Vaccine v1) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.system = system;
        this.v1 = v1;
        
        jLabel1.setText(enterprise.getName());
        jLabel3.setText(account.getUsername());
        populate();
    }
    
    public void populate() {
        txtName.setText(v1.getVaccineName());
        txtTime.setText(ft.format(v1.getCreatedTime()));
        txtType.setText(v1.getVaccineType());
        txtDetail.setText(v1.getDetail()); 
        for (Phase phase : v1.getPhases()) {
            jComboBox1.addItem(phase.getName());
        }
    }
    
    public void populatePhase(String phaseName) {
        for (Phase phase : v1.getPhases()) {
            if (phase.getName().equals(phaseName)) {
                txtStart.setText(phase.getStartDate() == null ? "" : ft.format(phase.getStartDate()));
                txtEnd.setText(phase.getEndDate() == null ? "" : ft.format(phase.getEndDate()));
                txtStatus.setText(phase.getStatus());
                if (phase.getEffectiveRate() == 0) {
                    txtRate.setText("0");
                } else {
                    String effective = phase.getEffectiveRate() + "%" + " (" + phase.getNumerator() + "/" + phase.getDenominator() + ")";
                    txtRate.setText(effective);
                }
                //txtRate.setText(String.valueOf(phase.getEffectiveRate()).equals("") ? "0" : String.valueOf(phase.getEffectiveRate()));
                txtDescription.setText(phase.getDescription());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetail = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtStart = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEnd = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtRate = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setEnabled(false);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Vaccine Name: ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 157, 128, 35));

        txtName.setEnabled(false);
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 157, 123, 35));

        jLabel5.setText("Create Time:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 212, 128, 35));

        txtTime.setEnabled(false);
        add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 212, 123, 35));

        jLabel6.setText("Detail: ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 333, 128, 35));

        txtDetail.setColumns(20);
        txtDetail.setRows(5);
        txtDetail.setEnabled(false);
        jScrollPane1.setViewportView(txtDetail);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 333, -1, 123));

        jLabel7.setText("Vaccine Type: ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 265, 128, 35));

        txtType.setEnabled(false);
        add(txtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 265, 123, 35));

        jLabel8.setText("Phase: ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 128, 35));

        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 136, 39));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, -1, 39));

        jLabel9.setText("Start Time: ");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 128, 35));

        txtStart.setEnabled(false);
        add(txtStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 136, 35));

        jLabel10.setText("End Time:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 128, 35));

        txtEnd.setEnabled(false);
        add(txtEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 136, 35));

        txtStatus.setEnabled(false);
        add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 138, 35));

        jLabel11.setText("Status: ");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 128, 35));

        jLabel12.setText("Effective Rate: ");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 128, 35));

        txtRate.setEnabled(false);
        add(txtRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 140, 35));

        jLabel14.setText("Description: ");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 128, 35));

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        txtDescription.setEnabled(false);
        jScrollPane2.setViewportView(txtDescription);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, -1, 123));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update Vaccine Info");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 596, 139, 40));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Save Vaccine Info");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 596, 139, 40));

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Vaccine Information Detail");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 574, 37));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 98, 83, 39));

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setText("Institution Name");

        jLabel2.setText("Welcome: ");

        jLabel3.setText("Scientist Username");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(329, 329, 329))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/u=2710482380,166887504&fm=26&gp=0.jpg"))); // NOI18N
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 700, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
//        ScientistWorkAreaJPanel panel = new ScientistWorkAreaJPanel(userProcessContainer, userAccount, organization, enterprise, system);
//        userProcessContainer.add("ScientistWorkAreaJPanel", panel);
//        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ScientistWorkAreaJPanel sysAdminwjp = (ScientistWorkAreaJPanel) component;
        sysAdminwjp.populate();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String selectedRow = jComboBox1.getSelectedItem().toString();
        populatePhase(selectedRow);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtName.setEnabled(true);
        txtType.setEnabled(true);
        txtDetail.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        v1.setVaccineName(txtName.getText());
        v1.setVaccineType(txtType.getText());
        v1.setDetail(txtDetail.getText());
        txtName.setEnabled(false);
        txtType.setEnabled(false);
        txtDetail.setEnabled(false);
        JOptionPane.showMessageDialog(null, "Vaccine updated successfully.");
        
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextArea txtDetail;
    private javax.swing.JTextField txtEnd;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRate;
    private javax.swing.JTextField txtStart;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTime;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables

}
