/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.WHOOfficerWorkArea;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Role.VolunteerManagerRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fengpeng
 */
public class ManageVolunteerManagerJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;
    private UserAccount selectedVolunteerManager;
    /**
     * Creates new form ManageDoctorsJPanel
     */
    public ManageVolunteerManagerJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 255));

        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.system = system;
        
        jLabel1.setText(enterprise.getName());
        jLabel3.setText(userAccount.getUsername());
        
        populateTable();
    }
    
    public void populateTable() {
        DefaultTableModel dtm=(DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        
        for (UserAccount userAccount : enterprise.getUserAccountDirectory().getUserAccountList()) {
            if (userAccount.getRole() instanceof VolunteerManagerRole) {
                Object[] row = new Object[3];
                row[0] = userAccount;
                row[1] = userAccount.getEmployee().getName();
                row[2] = userAccount.getPassword();
                
                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtUpdateName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtUpdateUsername = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtUpdatePassword = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Manager Name", "Manager Username", "Password"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 155, 794, 209));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Add a New Manager ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 397, 228, 36));

        jLabel5.setText("Name: ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 465, 108, 34));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 465, 102, 34));

        jLabel6.setText("Username: ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 515, 108, 34));
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 515, 102, 34));

        jLabel7.setText("Password: ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 567, 108, 34));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 567, 102, 34));

        createBtn.setBackground(new java.awt.Color(255, 255, 255));
        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 617, 228, 47));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Update a Manager Information ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 399, 228, 36));

        jLabel9.setText("Name: ");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 465, 108, 34));

        txtUpdateName.setEnabled(false);
        add(txtUpdateName, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 465, 102, 34));

        jLabel10.setText("Username: ");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 515, 108, 34));

        txtUpdateUsername.setEnabled(false);
        add(txtUpdateUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 515, 102, 34));

        jLabel11.setText("Password: ");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 567, 108, 34));

        txtUpdatePassword.setEnabled(false);
        add(txtUpdatePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 567, 102, 34));

        updateBtn.setBackground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 617, 95, 47));

        saveBtn.setBackground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 617, 95, 47));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Select");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(793, 394, 95, 47));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Volunteer Manager Information");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 118, 794, 28));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 73, -1, 40));

        jPanel5.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setText("WHO Officer");

        jLabel2.setText("Welcome: ");

        jLabel3.setText("WHO Officer Username");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(342, 342, 342))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/下載.jpg"))); // NOI18N
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 270, 260));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        String username = txtUserName.getText();
        if (system.getUserAccountDirectory().checkIfUsernameIsUnique(username)) {
            String name = txtName.getText();
        
            String password = txtPassword.getText();
            if (!name.equals("") && !username.equals("") && !password.equals("")) {
                Employee employee = enterprise.getEmployeeDirectory().createEmployee(name);
                UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new VolunteerManagerRole());
                //system.getUserAccountDirectory().getUserAccountList().add(account);
                populateTable();
            } else {
                JOptionPane.showMessageDialog(null, "Please fill in all updated information");
            }
        } else {
            JOptionPane.showMessageDialog(null, "This userAccount is already existed.");
        }
        
    }//GEN-LAST:event_createBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        if (!txtUpdateName.getText().equals("") && !txtUpdateUsername.getText().equals("") && !txtUpdatePassword.getText().equals("")) {
            selectedVolunteerManager.getEmployee().setName(txtUpdateName.getText());
            selectedVolunteerManager.setUsername(txtUpdateUsername.getText());
            selectedVolunteerManager.setPassword(txtUpdatePassword.getText());
            txtUpdateName.setEnabled(false);
            txtUpdateUsername.setEnabled(false);
            txtUpdatePassword.setEnabled(false);
            populateTable();
            JOptionPane.showMessageDialog(null, "updated successfully");
        } else {
            JOptionPane.showMessageDialog(null, "Please fill in all updated information");
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        txtUpdateName.setEnabled(true);
        txtUpdateUsername.setEnabled(true);
        txtUpdatePassword.setEnabled(true);
    }//GEN-LAST:event_updateBtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow(); 
        if (selectedRow >= 0) {
            selectedVolunteerManager = (UserAccount) jTable1.getValueAt(selectedRow, 0);
            txtUpdateName.setText(selectedVolunteerManager.getEmployee().getName());
            txtUpdateUsername.setText(selectedVolunteerManager.getUsername());
            txtUpdatePassword.setText(selectedVolunteerManager.getPassword()); 
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBtn;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUpdateName;
    private javax.swing.JTextField txtUpdatePassword;
    private javax.swing.JTextField txtUpdateUsername;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
