/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VolunteerWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Entity.Questionary;
import Business.Entity.User;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.VolunteerApplicationRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.DoctorWorkArea.VaccineShootRequestJPanel;

/**
 *
 * @author fengpeng
 */
public class VolunteerRegisterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VolunteerRegisterJPanel
     */
    private JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;
    private User user;
    public VolunteerRegisterJPanel() {
        
    }

    public VolunteerRegisterJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, EcoSystem system, User user) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.system = system;
        this.user = user;
        
        jLabel3.setText(userAccount.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupAlcoholic = new javax.swing.ButtonGroup();
        groupSmoking = new javax.swing.ButtonGroup();
        groupAllergic = new javax.swing.ButtonGroup();
        groupCold = new javax.swing.ButtonGroup();
        groupTest = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        radioAlcoholicYes = new javax.swing.JRadioButton();
        radioAlcoholicNo = new javax.swing.JRadioButton();
        radioSmokingNo = new javax.swing.JRadioButton();
        radioSmokingYes = new javax.swing.JRadioButton();
        radioAllergicNo = new javax.swing.JRadioButton();
        radioAllergicYes = new javax.swing.JRadioButton();
        radioColdNo = new javax.swing.JRadioButton();
        radioColdYes = new javax.swing.JRadioButton();
        radioTesNegitive = new javax.swing.JRadioButton();
        radioTestNo = new javax.swing.JRadioButton();
        radioTestPositive = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Volunteer Questionary");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 117, 710, 33));

        jLabel5.setText("Are you alcoholic? ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 178, 342, 34));

        jLabel6.setText("Are you Smoking?");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 242, 342, 34));

        jLabel7.setText("Have you ever had an allergic reaction? ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 308, 342, 34));

        jLabel8.setText("Do you have a cold? ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 376, 342, 34));

        jLabel9.setText("Do you get a covid-19 test? if yes, positive or negtive? ");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 437, -1, 34));

        radioAlcoholicYes.setBackground(new java.awt.Color(255, 255, 255));
        groupAlcoholic.add(radioAlcoholicYes);
        radioAlcoholicYes.setText("Yes");
        add(radioAlcoholicYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 178, -1, 34));

        radioAlcoholicNo.setBackground(new java.awt.Color(255, 255, 255));
        groupAlcoholic.add(radioAlcoholicNo);
        radioAlcoholicNo.setText("No");
        radioAlcoholicNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAlcoholicNoActionPerformed(evt);
            }
        });
        add(radioAlcoholicNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 178, -1, 34));

        radioSmokingNo.setBackground(new java.awt.Color(255, 255, 255));
        groupSmoking.add(radioSmokingNo);
        radioSmokingNo.setText("No");
        radioSmokingNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSmokingNoActionPerformed(evt);
            }
        });
        add(radioSmokingNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 242, -1, 34));

        radioSmokingYes.setBackground(new java.awt.Color(255, 255, 255));
        groupSmoking.add(radioSmokingYes);
        radioSmokingYes.setText("Yes");
        add(radioSmokingYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 242, -1, 34));

        radioAllergicNo.setBackground(new java.awt.Color(255, 255, 255));
        groupAllergic.add(radioAllergicNo);
        radioAllergicNo.setText("No");
        radioAllergicNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAllergicNoActionPerformed(evt);
            }
        });
        add(radioAllergicNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 308, -1, 34));

        radioAllergicYes.setBackground(new java.awt.Color(255, 255, 255));
        groupAllergic.add(radioAllergicYes);
        radioAllergicYes.setText("Yes");
        add(radioAllergicYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 308, -1, 34));

        radioColdNo.setBackground(new java.awt.Color(255, 255, 255));
        groupCold.add(radioColdNo);
        radioColdNo.setText("No");
        radioColdNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioColdNoActionPerformed(evt);
            }
        });
        add(radioColdNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 376, -1, 34));

        radioColdYes.setBackground(new java.awt.Color(255, 255, 255));
        groupCold.add(radioColdYes);
        radioColdYes.setText("Yes");
        add(radioColdYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 376, -1, 34));

        radioTesNegitive.setBackground(new java.awt.Color(255, 255, 255));
        groupTest.add(radioTesNegitive);
        radioTesNegitive.setText("Negtive");
        radioTesNegitive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTesNegitiveActionPerformed(evt);
            }
        });
        add(radioTesNegitive, new org.netbeans.lib.awtextra.AbsoluteConstraints(727, 437, -1, 34));

        radioTestNo.setBackground(new java.awt.Color(255, 255, 255));
        groupTest.add(radioTestNo);
        radioTestNo.setText("No");
        add(radioTestNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 437, -1, 34));

        radioTestPositive.setBackground(new java.awt.Color(255, 255, 255));
        groupTest.add(radioTestPositive);
        radioTestPositive.setText("Positive");
        add(radioTestPositive, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 437, -1, 34));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 515, 137, 50));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 69, -1, 38));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setText("Normal User");

        jLabel2.setText("Welcome: ");

        jLabel3.setText("Normal User Username");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/volunteer2.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 540, 340));
    }// </editor-fold>//GEN-END:initComponents

    private void radioAlcoholicNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAlcoholicNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioAlcoholicNoActionPerformed

    private void radioSmokingNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSmokingNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioSmokingNoActionPerformed

    private void radioAllergicNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAllergicNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioAllergicNoActionPerformed

    private void radioColdNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioColdNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioColdNoActionPerformed

    private void radioTesNegitiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTesNegitiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioTesNegitiveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (groupAlcoholic.getSelection() != null && groupAllergic.getSelection() != null && groupCold.getSelection() != null && groupSmoking.getSelection() != null && groupTest.getSelection() != null) {
            Questionary questionary = new Questionary();
            if (radioAlcoholicNo.isSelected()) {
                questionary.setIsAlcoholic(false);
            }
            if (radioAlcoholicYes.isSelected()) {
                questionary.setIsAlcoholic(true);
            }
            if (radioAllergicNo.isSelected()) {
                questionary.setIsAllergic(false);
            }
            if (radioAllergicYes.isSelected()) {
                questionary.setIsAllergic(true);
            }
            if (radioColdNo.isSelected()) {
                questionary.setIsCold(false);
            }
            if (radioColdYes.isSelected()) {
                questionary.setIsCold(true);
            }
            if (radioSmokingNo.isSelected()) {
                questionary.setIsSmoking(false);
            }
            if (radioSmokingYes.isSelected()) {
                questionary.setIsSmoking(true);
            }
            if (radioTestNo.isSelected()) {
                questionary.setTestResult("No");
            }
            if (radioTestPositive.isSelected()) {
                questionary.setTestResult("Positive");
            }
            if (radioTesNegitive.isSelected()) {
                questionary.setTestResult("Negitive");
            }
            
            WorkRequest application = new VolunteerApplicationRequest(questionary, false, "");
            ((VolunteerApplicationRequest)application).setSender(userAccount);
            ((VolunteerApplicationRequest)application).setUser(user);
            ((VolunteerApplicationRequest)application).setStatus("Requested");
            
            system.getWorkQueue().getWorkRequestList().add(application);
            JOptionPane.showMessageDialog(null, "reported successfully.");
        } else {
            JOptionPane.showMessageDialog(null, "Please fill out the questionary");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup groupAlcoholic;
    private javax.swing.ButtonGroup groupAllergic;
    private javax.swing.ButtonGroup groupCold;
    private javax.swing.ButtonGroup groupSmoking;
    private javax.swing.ButtonGroup groupTest;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radioAlcoholicNo;
    private javax.swing.JRadioButton radioAlcoholicYes;
    private javax.swing.JRadioButton radioAllergicNo;
    private javax.swing.JRadioButton radioAllergicYes;
    private javax.swing.JRadioButton radioColdNo;
    private javax.swing.JRadioButton radioColdYes;
    private javax.swing.JRadioButton radioSmokingNo;
    private javax.swing.JRadioButton radioSmokingYes;
    private javax.swing.JRadioButton radioTesNegitive;
    private javax.swing.JRadioButton radioTestNo;
    private javax.swing.JRadioButton radioTestPositive;
    // End of variables declaration//GEN-END:variables
}
