/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.TesterWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Entity.Animal;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ScientistRequestTesterRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class TesterWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;
    private WorkRequest selectedRequest;
    private SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public TesterWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 255));

        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.system = system;
        
        jLabel1.setText(enterprise.getName());
        jLabel3.setText(account.getUsername());
        
        
        
        
        populate();     
    }
    
   

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDetail = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtRate = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setEnabled(false);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Vaccine Name", "Vaccine Type", "Create Time", "Phase", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 120, 831, 211));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Vaccine Pre-clinical Test Request");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 78, 831, 36));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Select");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 367, -1, 41));

        jLabel5.setText("Vaccine Name: ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 434, 128, 35));

        txtName.setEnabled(false);
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 434, 123, 35));

        jLabel6.setText("Create Time:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 487, 128, 35));

        txtTime.setEnabled(false);
        add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 487, 123, 35));

        jLabel7.setText("Vaccine Type: ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 434, 192, 35));

        txtType.setEnabled(false);
        add(txtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 434, 123, 35));

        jLabel8.setText("Detail: ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 547, 128, 35));

        txtDetail.setColumns(20);
        txtDetail.setRows(5);
        txtDetail.setEnabled(false);
        jScrollPane2.setViewportView(txtDetail);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 547, -1, 123));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Go To Test");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 629, -1, 41));

        jLabel9.setText("Preclinical Effective Rate: ");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 495, 192, 35));

        txtRate.setEnabled(false);
        add(txtRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 495, 53, 35));

        jLabel13.setText("%");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 497, 103, 30));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Report to Admin");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 367, 215, 41));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setText("Institution Name");

        jLabel2.setText("Welcome: ");

        jLabel3.setText("Tester Username");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 384, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Vaccine1.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, 400, 200));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
//        int selectAccept = jTable1.getSelectedRow();
//        if (selectAccept >= 0) {
//            Vaccine v2 = (Vaccine)jTable1.getValueAt(selectAccept, 0);
//            if ("accept".equals(v2.getStatus())) {
//                PreclinicalTestJPanel panel = new PreclinicalTestJPanel(userProcessContainer, userAccount, organization, enterprise, system, v2);
//                userProcessContainer.add("InstitutionAdminWorkAreaJPanel", panel);
//                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
//                layout.next(userProcessContainer);
//            }
//            else {
//                JOptionPane.showMessageDialog(null, "please accept");
//            return;
//            }
//        }
//        else {
//            JOptionPane.showMessageDialog(null, "Please select a row");
//            populate();
//        }
//        return;

        if (selectedRequest != null) {
            ((ScientistRequestTesterRequest)selectedRequest).getVaccine().getPhases().get(0).setStatus("Testing");
            PreclinicalTestJPanel panel = new PreclinicalTestJPanel(userProcessContainer, userAccount, organization, enterprise, system, selectedRequest);
            userProcessContainer.add("InstitutionAdminWorkAreaJPanel", panel);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
        txtDetail.setText("");
        txtName.setText("");
        txtRate.setText("");
        txtTime.setText("");
        txtType.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        int selectAccept = jTable1.getSelectedRow();
//        int total = 0;
//        int number = 0;
//        if (selectAccept >= 0) {
//            Vaccine v1 = (Vaccine)jTable1.getValueAt(selectAccept, 0);
//            v1.setStatus("accept");
//
//            txtName.setText(v1.getVaccineName());
//            txtType.setText(v1.getVaccineType());
//            txtDetail.setText(v1.getDetail());
//            txtTime.setText(v1.getCreatedTime());
//            for (Animal a : v1.getAnimalDirectory().getAnimalList()) 
//            {
//                total += a.getTotal();
//                number += a.getNumber();
//            }
//            if (number == 0) {
//                txtRate.setText("0");
//            }
//            else {
//                txtRate.setText(String.valueOf(((number*100)/total)));
//            }
//            populate();
//        }
//        else {
//            JOptionPane.showMessageDialog(null, "Please select a row");
//            populate();
//        }
//        return;

        int selectedRow = jTable1.getSelectedRow();
        int total = 0, number = 0;
        if (selectedRow >= 0) {
            selectedRequest = (WorkRequest)jTable1.getValueAt(selectedRow, 0);
            txtName.setText(((ScientistRequestTesterRequest)selectedRequest).getVaccine().getVaccineName());
            txtType.setText(((ScientistRequestTesterRequest)selectedRequest).getVaccine().getVaccineType());
            txtDetail.setText(((ScientistRequestTesterRequest)selectedRequest).getVaccine().getDetail());
            txtTime.setText((ft.format(((ScientistRequestTesterRequest)selectedRequest).getVaccine().getCreatedTime())));
            
            for (Animal a : ((ScientistRequestTesterRequest)selectedRequest).getVaccine().getAnimalDirectory().getAnimalList()) 
            {
                total += a.getTotal();
                number += a.getNumber();
            }
            if (number == 0) {
                txtRate.setText("0");
            }
            else {
                txtRate.setText(String.valueOf(((number*100)/total)));
                int size = ((ScientistRequestTesterRequest)selectedRequest).getVaccine().getPhases().size();
                ((ScientistRequestTesterRequest)selectedRequest).getVaccine().getPhases().get(size-1).setEffectiveRate(((number*100)/total));
            }
            
            populate();
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ((ScientistRequestTesterRequest)selectedRequest).getVaccine().getPhases().get(0).setEndDate(new Date());
        ((ScientistRequestTesterRequest)selectedRequest).getVaccine().getPhases().get(0).setStatus("Reported");
        ((ScientistRequestTesterRequest)selectedRequest).setIsTested(true);
        txtDetail.setText("");
        txtName.setText("");
        txtRate.setText("");
        txtTime.setText("");
        txtType.setText("");
        populate();
        JOptionPane.showMessageDialog(null, "Report to Admin");
        
        
                
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea txtDetail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRate;
    private javax.swing.JTextField txtTime;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables

//    private void populate() {
//        DefaultTableModel dtm=(DefaultTableModel) jTable1.getModel();
//        dtm.setRowCount(0);
//
//        if (enterprise.getVaccineDirectory().getVaccineList() == null) {
//            System.out.println("null");
//        }
//        
//        for (Vaccine vaccine : enterprise.getVaccineDirectory().getVaccineList()) {
//            if ("request phase 1".equals(vaccine.getStatus()) || "accept".equals(vaccine.getStatus())) {
//                Object[] row = new Object[5];
//                row[0] = vaccine;
//                row[1] = vaccine.getVaccineType();
//                row[2] = vaccine.getCreatedTime();
//                row[4] = vaccine.getStatus();
//                int size = vaccine.getPhases().size();
//                if (size == 0) {
//                    dtm.addRow(row);
//                } else {
//
//                    row[3] = vaccine.getPhases().get(vaccine.getPhases().size()-1).getName();
//                    row[4] = vaccine.getStatus();
//                    dtm.addRow(row);
//                }
//            }
//            
//        }
//    }
    
    public void populate() {
        DefaultTableModel dtm=(DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        
        for (WorkRequest request : system.getWorkQueue().getScientistRequestTesterByEnterprise(enterprise)) {
            ScientistRequestTesterRequest scientistRequest = (ScientistRequestTesterRequest)request;
            if (!scientistRequest.isIsTested()) {
                Object[] row = new Object[5];
                row[0] = scientistRequest;
                row[1] = scientistRequest.getVaccine().getVaccineType();
                row[2] = ft.format(scientistRequest.getVaccine().getCreatedTime());
                row[3] = scientistRequest.getVaccine().getPhases().get(scientistRequest.getVaccine().getPhases().size()-1).getName();
                row[4] = scientistRequest.getVaccine().getStatus();
                dtm.addRow(row);
            }
            

    }
    }
}
